In [ ]:
pip install numpy

In [50]:
import numpy as np


In [ ]:
## 1d array 

a=np.array([1,2,3,4,5])
print(type(a))
print(a.shape)
a2=a.reshape(1,5)
a2

### this is 2 dimension array as [[ are there at starting and closing 

In [ ]:
a2.shape

In [ ]:
a3=np.array([[1,2,3,4],[3,4,5,7]])
a3.shape

## 2 dimesnion array as with shape as 2 rows and 4 columns 

In [ ]:
np.arange(1,10,2).reshape(1,5)


In [ ]:
np.arange(1,10,2).reshape(5,1)

In [ ]:
np.ones((3,6))

In [ ]:
np.eye((5))

In [ ]:
a1=np.array([1,2,3,4,5])
a2=np.array([10,23,4,5,2])

### element wise addition , sub , multipication, divison
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a2*a2)

In [ ]:
## Universal Functions 


print(np.sqrt(a2))

print(np.exp(a2))

print(np.sin(a2))

print(np.log(a2))

In [ ]:
## array slicing 

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

arr

In [47]:
print(arr[1:2,0:2])

[[5 6]]


In [ ]:
print(arr[0][0])

In [ ]:
# print(arr[1:])
print(arr[1:,2:])

In [57]:
arr=np.array([[1,2,3,4],[4,5,6,7],[2,8,7,4]])
print(type(arr))

<class 'numpy.ndarray'>


In [59]:
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [2, 8, 7, 4]])

In [60]:
arr[1:,0:2]

array([[4, 5],
       [2, 8]])

In [64]:
# modifying array elements 
arr[0,0]=10
arr

array([[10,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 2,  8,  7,  4]])

In [67]:
## statistical concepts normalization

## logical operation

a=np.array([1,2,3,4,5,6,7,89])

a[a>5]

array([ 6,  7, 89])